# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: golang
        uses: cedrickring/golang-action@1.5.1
        env:
          GO111MODULE: "on"
          PROJECT_PATH: "herge-lab"
        with:
          args: (cd herge-lab ; go mod vendor)
      - name: heroku
	working-directory: ./herge-lab
        uses: akhileshns/heroku-deploy@v3.0.0 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "herge-lab" #Must be unique in Heroku
          heroku_email: "gabrielradureau@gmail.com"
          usedocker: true
