# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Set github token to access private repo
        run: git config --global url."https://radureau:${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: golang dependencies
        env:
          GO111MODULE: "on"
          GOPRIVATE: "github.com/radureau/my-heroku-app-pkg"
        run: go version && go mod vendor
        working-directory: herge-lab

      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a herge-lab web --arg GITHUB_ACCESS_TOKEN=${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
        working-directory: herge-lab
      - name: Release
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a herge-lab web
        working-directory: herge-lab